all: bidding_system host player player_bonus
bidding_system: bidding_system.c
	cc bidding_system.c -o bidding_system
host: host.c
	cc host.c -o host
player: player.c
	cc player.c -o player
player_bonus: player_bonus.c
	cc player_bonus.c -o player_bonus
clean:
	rm bidding_system host player player_bonus
